package energy;

// Generated 2012-8-20 16:24:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orginfo generated by hbm2java
 */
public class Orginfo implements java.io.Serializable {

	private String orgId;
	private String orgName;
	private Date createTime;
	private Set users = new HashSet(0);

	public Orginfo() {
	}

	public Orginfo(String orgId, String orgName, Date createTime) {
		this.orgId = orgId;
		this.orgName = orgName;
		this.createTime = createTime;
	}

	public Orginfo(String orgId, String orgName, Date createTime, Set users) {
		this.orgId = orgId;
		this.orgName = orgName;
		this.createTime = createTime;
		this.users = users;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
